language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: Hp6tOlXFyke8etMpiOMSKegiDbxFyL9ysSrttWzWkXwJW4uLp04XOOdWZ8MsN1KmhM66dLybpC5UiJO9WOHvOxS/HjvcRAceXkchssTRI9LrnS0qg1xuao8GeLt9IglOEWpl6PU03IAvaf8/13M8AQMqAeyn0zR55Ei9R/njF1UzME+5zrm2x8j7PbteM9yko9TcXBYs8h4pI2fVjJYTid9odp72xQDS2IfNIvCFHfBWjywe4kRU3rumjkiJkXnPbImer6yaBidt2kDexMqrMjxsgB+2Kow3JEyIYdQUhESbHRuybY8gN9E48mCBanSjJX0xkD3RvjHx2whyMsIoJNvFRgDZAa01lhN/xtnKBCzoF4CFahPqSiVLgFJjfTmc02OVYbHIspqj0AE8W/16ThoL98I+Lum1WVp5Ucl722WEKeFwe19qBybvq0bMci/I9YZk6CAE62srBd9xHwcGGlUOdtOGY/Rs5lKhjrP911jbYj/cnA5i+r/QD2W1k6Dw5+10Ai1Uo6S67ijAvmF+J+yD8zo8gpC8T0EQVkombyn2t6N3SqsBbfJLr6L0h6V4+OjdJGvABqjROJLGXW+sjcsA72KTRfLtu7UBXb0H9o96Z7HHA3+Mnol8UqruViNA8FPUJs2vpDREP24iOFX7ygQzucAfr28xaOQ1Nba5LMk=
  app: VRAD
  skip-cleanup: true
