language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: caPPbINg+No8MZh3NFHXhM1Ftwj8h/7RPHVYZruNFimooT/FkNqCLgE9FS5tHUAuypjakwESbqwZb6d899Aavo7zPZ4iZzHEa3/ge2ZPxkPzh6fKnXrxkwkZbeIMp3kWym6iQ8zgtK6GEGjWUNZ9XmM5pGbBcyHzQ/l4Uzevo/6uG5AC8H0wONapwgQamHB6RChCEsLmFag+CCYFpZGE6r2aKrzfdf7kM4hpMnaEvTCNY7R/gbhsOebWXpNIr5dTqHZ5Ypbce9xU4IiaxTQ51/2RXN2BHBOVmmwxVXMMY8ph0yponJD0e1LzbOOPd53fTAH0f9BzYHmsVv+NV4QUcb8YLVyrQ/kj3foHLTVzPyhVNRBNY2D9EaE505x7Ov14jSP8fobTV/m8RYG2Tug9kVBfajy3xUWduaPik7BW8RjjHPDS0+i/O+DEhbZXmSj3cFm0xeBpGmAHX3jgMMW4jtoc0cy0rgdC3qofEXK963TLcC75JfTWpkpP87PvBsoUY0RjL8dfYsfF79vF5sVybXSZaDImUYJp/uzUXU9ifrnHpA6NaajFY0BNePmNdQxziWBKYKl8AhwHq/cmVMWRvEQgtg3tgkuKM2LUf1qP0a4bGU4DtMgD3nZY4wWQkKDQWjcD+GYyW5aGdeb6YKS4LbabAfNvcy9T9YajKwyZOe4=
  app: VRAD
  skip-cleanup: true
